version: '3'

services:

  frontend:
    build: ./frontend
    container_name: roque-one-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    command: serve -s build -l 3000


  api:
    build: ./api
    container_name: roque-one-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=http://realworld.com
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_db
    networks:
      - docker-up

  auth:
    build: ./auth
    container_name: roque-one-auth
    command: npm run start
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - HOST=http://realworld.com
      - MONGO_URL=mongodb://api_db:27017/auth
      - API_URL=http://api:3001/api
    networks:
      - docker-up

  api_db:
    image: mongo:latest
    container_name: roque-one-api-db
    volumes:
      - mongodb_api:/data/db
    networks:
      - docker-up

  auth_db:
    image: mongo:latest
    container_name: roque-one-auth-db
    volumes:
      - mongodb_auth:/data/db
    networks:
      - docker-up    

  nginx:
    image: nginx:stable-alpine
    container_name: roque-one-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
    networks:
      - docker-up

volumes:
    mongodb_api:
    mongodb_auth:

networks:
  docker-up:
    driver: bridge
